### PR TITLE
Show nep5 symbol

### LINKED ISSUE #140: Show NEP-5 symbol next to balance
It's awesome that neoscan supports NEP-5 tokens now. Nice work! One added touch that would be nice is if you displayed the token symbol next to the balance since people will be used to seeing the symbol (and not necessarily always the token name). I think it's cool having the token name as the header as you have right now, but it might be a nice added touch to show the symbol next to the balance displayed. 👍

### PR DESCRIPTION
**Pull request by adrienmo**
close #140

### CODE REVIEW

**Comment by christophe238** [comment]
Thanks @adrienmo do we have any estimate of when this can be available to everyone on the API?

**Comment by adrienmo** [comment]
@christophe238 it's deployed !

**Comment by adrienmo** [comment]
@christophe238 actually api is rollbacked because it breaks neon-js for an unknown reason.

**Comment by christophe238** [comment]
Thanks for the update!

**Pull request merged**
