### PR TITLE
Use env variables to set up the app

### PR DESCRIPTION
**Pull request by vladucu**
Currently, when you clone the app, you have to edit `apps/neoscan/config/dev.exs` and set you DB username & password marking the tree dirty.

This uses env variables to configure things instead. If you like this and want to merge, some variables need to be setup
on Heroku before pushing:

* MIX_ENV=prod
* URL_HOST=neoscan.io
* DATABASE_POOL_SIZE=30
* SECRET_KEY_BASE

Tested on a new Heroku app and seemed to work fine.

Also, sets a `45_000ms` timeout for websocket transport to avoid issues with Heroku’s 55-second timeout window, as suggested on [HexDocs](https://hexdocs.pm/phoenix/heroku.html)

### CODE REVIEW

**Comment by steffenix** [comment]
I am more for using docker everywhere and we won't need to configure env for each local devs.

**Comment by lucianoengel** [comment]
We are currently not running this on heroku. We had a branch using env vars but it was deleted when we got rid of heroku.  It's very nice that you are interested in contributing to the project, feel free to contact me if you want to know more about it.

**Comment by vladucu** [comment]
Thx guys, sounds good!

@lucianoengel where can we connect best? on `#develop` slack channel?

**Comment by lucianoengel** [comment]
You can talk to me directly! @luciano_engel

**Pull request closed without merging**
